# UTS-2 My Songs for You

Living Millennium

Lirik by Wisyendra Lunarmalam

Music: Iyowa

[Living Millennium](https://drive.google.com/file/d/13jVECsLIPkNbWteOT_9m8Jjpwl9rlKWS/view?usp=sharing).

Aaa~  
Aku hidup seribu tahun di matamu  
Waktu berhenti tiap kamu menatap  
Di dunia tanpa logika  
Hanya kau yang terasa nyata  
Tapi aku hanya ingin dikenang olehmu  

Aku lupa hari tapi aku ingat suaramu  
Satu-satunya data yang tidak bisa kuhapus  
Kalau hidup ini hanyalah sementara  
Maka kamu adalah error yang ingin kutahan selamanya  

Seribu tahun lagi pun tidak cukup  
Untuk mengurai makna dari dirimu  
Rattatta kalau aku crash, tolong simpan memoriku  

Kadang jantung dan tubuhku ini menolak  
Agaknya sebuah oxymoron bukan?  
Tapi bahkan di ujung detak jantung terakhirku  
Aku tahu aku masih ingin bersamamu  

Seribu tahun lagi pun tidak akan cukup  

Mungkin nanti ku akan jadi bayangan ataupun sinyal yang aneh  
Itu aku yang masih berusaha hidup bersamamu  
Seribu tahun aku di dalam dirimu  
Aku tersesat tapi tak ingin pulang  

Ketika semua sistem berhenti  
Sisa diriku di matamu  
Tapi itu cukup karena di situ aku abadi  

Seribu tahun lagi  